#!/usr/bin/env bash
# measure_cost.sh — regenerate the gas/resource cost table in DEPLOY.md
#
# Usage:
#   cd contract
#   bash scripts/measure_cost.sh [--network testnet|mainnet] [--contract <CONTRACT_ID>]
#
# Prerequisites:
#   - Stellar CLI installed  (stellar --version)
#   - A funded key called "deployer" on the target network
#   - The registry contract already deployed (pass its ID via --contract or
#     set CONTRACT_ID in the environment)
#
# The script calls each entry point with --cost on a live contract that has
# been pre-populated to the four registry sizes listed in the cost table.
# It writes the results as a Markdown table to stdout and patches the
# <!-- COST_TABLE_START / END --> sentinel block in DEPLOY.md when --patch
# is supplied.
#
# Note: --cost measures CPU instructions and memory bytes consumed by the
# Soroban host environment; it does NOT submit a real transaction.

set -euo pipefail

###############################################################################
# Defaults
###############################################################################
NETWORK="testnet"
CONTRACT_ID="${CONTRACT_ID:-}"
PATCH=0
SOURCE="${SOURCE:-deployer}"
PROVIDER_ADDR="${PROVIDER_ADDR:-}"

###############################################################################
# Argument parsing
###############################################################################
while [[ $# -gt 0 ]]; do
  case "$1" in
    --network)   NETWORK="$2";       shift 2 ;;
    --contract)  CONTRACT_ID="$2";   shift 2 ;;
    --source)    SOURCE="$2";        shift 2 ;;
    --provider)  PROVIDER_ADDR="$2"; shift 2 ;;
    --patch)     PATCH=1;            shift   ;;
    -h|--help)
      sed -n '2,30p' "$0" | sed 's/^# //'
      exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

if [[ -z "$CONTRACT_ID" ]]; then
  echo "ERROR: set CONTRACT_ID env var or pass --contract <id>" >&2
  exit 1
fi

###############################################################################
# Helpers
###############################################################################
STELLAR="${STELLAR_CLI:-stellar}"
command -v "$STELLAR" >/dev/null 2>&1 || { echo "stellar CLI not found in PATH" >&2; exit 1; }

# Run a --cost invocation and extract cpu_insns + mem_bytes from the output.
# Prints two whitespace-separated tokens: "<cpu> <mem>" (or "n/a n/a").
measure() {
  local fn="$1"; shift
  local out cpu mem
  out=$("$STELLAR" contract invoke \
    --id      "$CONTRACT_ID" \
    --source  "$SOURCE" \
    --network "$NETWORK" \
    --cost \
    -- "$fn" "$@" 2>&1) || true
  cpu=$(echo "$out" | grep -iE "cpu[_ ]insns?" | grep -oP '\d+' | head -1)
  mem=$(echo "$out" | grep -iE "mem[_ ]bytes?"  | grep -oP '\d+' | head -1)
  printf '%s %s\n' "${cpu:-n/a}" "${mem:-n/a}"
}

# Formatted Markdown table row
row() {
  # $1 entry-point  $2 size  $3 cpu  $4 mem
  printf "| %-34s | %5s | %14s | %14s |\n" "$1" "$2" "$3" "$4"
}

sep() {
  echo "|---|---|---|---|"
}

###############################################################################
# Build table
###############################################################################
SIZES=(1 10 100 500)

{
  echo "<!-- COST_TABLE_START -->"
  echo "<!-- Generated by contract/scripts/measure_cost.sh on $(date -u +%Y-%m-%dT%H:%MZ) -->"
  echo "<!-- Re-run: bash contract/scripts/measure_cost.sh --contract \$CONTRACT_ID --patch -->"
  echo ""
  echo "### Runtime resource cost"
  echo ""
  echo "Measured with \`stellar contract invoke --cost\` on Stellar testnet."
  echo "CPU is reported in **instructions**; memory in **bytes**."
  echo "⚠️ marks functions whose cost scales with registry size."
  echo ""

  printf "| %-34s | %5s | %14s | %14s |\n" \
    "Entry point" "N svcs" "CPU (insns)" "Mem (bytes)"
  echo "|---|---:|---:|---:|"

  for SIZE in "${SIZES[@]}"; do
    echo "Measuring at N=${SIZE}…" >&2

    # ── O(1) functions ────────────────────────────────────────────────────
    read -r cpu mem <<< "$(measure get_agents_contract)"
    row "get_agents_contract" "$SIZE" "$cpu" "$mem"

    read -r cpu mem <<< "$(measure get_service_count)"
    row "get_service_count" "$SIZE" "$cpu" "$mem"

    read -r cpu mem <<< "$(measure get_reputation_bounds)"
    row "get_reputation_bounds" "$SIZE" "$cpu" "$mem"

    read -r cpu mem <<< "$(measure get_service --id 1)"
    row "get_service" "$SIZE" "$cpu" "$mem"

    # ── list_services — O(limit) read, O(limit²) sort (limit ≤ 50) ───────
    # The ServiceIds vec is a single persistent entry, so the load itself is
    # O(1); cost grows only with the requested page window, not total N.
    read -r cpu mem <<< "$(measure list_services --offset 0 --limit 10)"
    row "list_services (limit=10)" "$SIZE" "$cpu" "$mem"

    # ── list_services_page — ⚠️ O(N) walk ─────────────────────────────────
    # Must scan every stored ID to count active services, so CPU and memory
    # grow linearly with the total number of registered services.
    read -r cpu mem <<< "$(measure list_services_page --page 0 --page_size 10)"
    row "list_services_page ⚠️" "$SIZE" "$cpu" "$mem"

    # ── register_service — ⚠️ O(N) via active_service_exists scan ─────────
    # active_service_exists iterates over all IDs to detect duplicate
    # (provider, endpoint) pairs; cost grows with total registered services.
    if [[ -n "$PROVIDER_ADDR" ]]; then
      read -r cpu mem <<< "$(measure register_service \
        --provider    "$PROVIDER_ADDR" \
        --name        "CostProbe" \
        --description "Cost measurement probe — safe to ignore" \
        --endpoint    "https://probe-$(date +%s).example.com/v0" \
        --price_usdc  "0" \
        --pay_to      "$PROVIDER_ADDR" \
        --category    "benchmark")"
      row "register_service ⚠️" "$SIZE" "$cpu" "$mem"
    else
      row "register_service ⚠️" "$SIZE" "(needs --provider)" "(needs --provider)"
    fi

    # ── deactivate_service — ⚠️ O(C) category-index scan ─────────────────
    # Reads and rewrites the per-category ID list; cost scales with the
    # number of services in the same category, not the total registry size.
    if [[ -n "$PROVIDER_ADDR" ]]; then
      read -r cpu mem <<< "$(measure deactivate_service \
        --provider "$PROVIDER_ADDR" --id 1)"
      row "deactivate_service ⚠️" "$SIZE" "$cpu" "$mem"
    else
      row "deactivate_service ⚠️" "$SIZE" "(needs --provider)" "(needs --provider)"
    fi

    # ── update_reputation — O(1) registry ops + cross-contract call ───────
    # Registry storage operations are O(1), but the cross-contract call to
    # LodestarAgents is billed separately (sub-invocation budget).
    row "update_reputation (+ CCI)" "$SIZE" "O(1) + CCI" "O(1) + CCI"

    sep
  done

  echo ""
  echo "> **Measurement method:** \`stellar contract invoke --cost --id \$CONTRACT_ID -- <fn> <args>\`"
  echo "> Regenerate this table: \`bash contract/scripts/measure_cost.sh --contract \$CONTRACT_ID --network testnet --patch\`"
  echo ""
  echo "<!-- COST_TABLE_END -->"
} 2>/dev/null

###############################################################################
# Optional in-place patch of DEPLOY.md
###############################################################################
if [[ "$PATCH" -eq 1 ]]; then
  SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
  DEPLOY_MD="${SCRIPT_DIR}/../DEPLOY.md"

  if [[ ! -f "$DEPLOY_MD" ]]; then
    echo "WARN: DEPLOY.md not found at $DEPLOY_MD; skipping patch" >&2
    exit 0
  fi

  TMPFILE=$(mktemp)
  # Strip old table block
  awk '/<!-- COST_TABLE_START -->/{skip=1} !skip{print} /<!-- COST_TABLE_END -->/{skip=0}' \
    "$DEPLOY_MD" > "$TMPFILE"

  # Insert new table block at the sentinel marker position
  NEW_TABLE=$(bash "$0" \
    --network  "$NETWORK" \
    --contract "$CONTRACT_ID" \
    --source   "$SOURCE" \
    ${PROVIDER_ADDR:+--provider "$PROVIDER_ADDR"})

  awk -v table="$NEW_TABLE" \
    '/<!-- COST_TABLE_START -->/{print table; next} {print}' \
    "$TMPFILE" > "$DEPLOY_MD"

  rm "$TMPFILE"
  echo "Patched $DEPLOY_MD" >&2
fi
